### ISSUE TITLE
Perprop leaks memory

### ISSUE THREAD

**Issue by ggrieco-tob** [trailofbits/echidna#100]
If you run `perprop-exe` any solidity contract, like this one:

```solidity
contract C {
  function f(uint x) returns (uint) { return x; }
  function test() returns (bool) {
    return true;
  }
}
```

using this config file:

```yaml
testLimit: 10
sender:
    - address: 0x1
      name: 'sender'
properties:
    - name: 'test'
      return: 'Success'
```

It will cause a noticeable memory leak (use `top` to check it). Depending on your system configuration, your OS can kill automatically the `perprop-exe` execution.
