### ISSUE TITLE
Define contract deployer

### ISSUE THREAD

**Issue by asymmetric** [trailofbits/echidna#146]
I'd like to be able to control the address that creates my contracts.

Since echidna uses hevm in the background, I had a look at the source and found [this variable](https://github.com/dapphub/dapptools/blob/920bf4c528ceac5b32f0050aa0af0784d0349ca1/src/hevm/src/EVM/Exec.hs#L18), which in hevm is both the [origin and the caller](https://github.com/dapphub/dapptools/blob/920bf4c528ceac5b32f0050aa0af0784d0349ca1/src/hevm/src/EVM/Exec.hs#L27-L28).

This is [overridden](
https://github.com/trailofbits/echidna/tree/558dc71b1f1804100c5e819e6446f7558bfc3fce/lib/Echidna/Config.hs#L46) to be the contract's address, whereas the caller is [overridden here](
https://github.com/trailofbits/echidna/tree/558dc71b1f1804100c5e819e6446f7558bfc3fce/lib/Echidna/Solidity.hs#L108) to be the same as the sender.

It's not clear to me what the best way to define the "origin" is - or whaterver field corresponds to the idea of a deployer.

It would be super cool if these defaults could be mentioned somewhere in the README too :)

**Comment by ggrieco-tob** [comment]
We have a configuration option called `deployer`. Is that what you need?

**Comment by emavgl** [comment]
> We have a configuration option called `deployer`. Is that what you need?

Hi @ggrieco-tob my configuration file has these fields:

```yaml
#Contract's address in the EVM
contractAddr: "0x00a329c0648769a73afac7f9381e08fb43dbea72"

#Sender's address in the EVM
# sender == deployer
deployer: "0x00a329c0648769a73afac7f9381e08fb43dbea70"
sender: "0x00a329c0648769a73afac7f9381e08fb43dbea70"

#List of addresses that will be used in all tests
addrList: ["0x0000000000000000000000000000000000000010", "0x0000000000000000000000000000000000000001", "0x0000000000000000000000000000000000000002", "0x0000000000000000000000000000000000000004", "0x0000000000000000000000000000000000000005", "0x0000000000000000000000000000000000000006", "0x0000000000000000000000000000000000000007", "0x0000000000000000000000000000000000000008", "0x0000000000000000000000000000000000000009"]
```

Even if the field **deployer** is set; testing a contract that extends the contract  `owned`

```javascript
contract owned { address public owner;
  function owned() {
      owner = msg.sender;
  }

  modifier onlyOwner {
      require(msg.sender == owner);
      _;
  }

  function transferOwnership(address newOwner) onlyOwner {
      owner = newOwner;
  }
}
```
causes the following invariant to fail at the first call

```javascript
    function echidna_invariant_I0() public returns (bool) {
        address config_deployer = 0x00a329c0648769a73afac7f9381e08fb43dbea70;
        return owner == config_deployer;
    }
```

instead, this one never fails

```javascript
    function echidna_invariant_I0() public returns (bool) {
        address config_contract_addr = 0x00a329c0648769a73afac7f9381e08fb43dbea72;
        return owner == config_contract_addr;
    }
```

Am I using the `deployer` parameter in the right way?
