### ISSUE TITLE
Perprop config parsing

### ISSUE THREAD

**Issue by james9909** [trailofbits/echidna#84]
When perprop parses a config for function names, it doesn't separate the name from the rest of the signature. This results in echidna trying to run a function named (for example) "test()" instead of "test".

**Comment by ggrieco-tob** [comment]
I believe #89 is not solving this issue. If we have a simple contract:

```solidity
contract C {
  function f() { }
  function test() returns (bool) {
    return true;
  }
}
```
and a minimal config file:

```yaml
testLimit: 2
sender:
    - address: 0x1
      name: 'sender'
properties:
    - name: 'test()'
      return: 'Success'
```
perprop-exe won't work as expected:

```bash
$ perprop-exe test.sol test.yaml 
...
"Analyzing contract: test.sol:C"
perprop-exe: Property test() not found in ABI
CallStack (from HasCallStack):
  error, called at perprop/Main.hs:137:14 in main:Main
```
